# Generated by Django 4.1.4 on 2022-12-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctions_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='auction_id',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='user_id',
            new_name='user',
        ),
    ]
